itsc_celulares/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name="home"),
    path('login/', views.login_page, name="login"),
    path('logout', views.logout_user, name="logout"),
    path('users/', views.users, name="users"),
    path('users/new', views.register_new_user, name="new"),
    path('users/remove/<str:pk>', views.remove_user, name="remove-user"),
    path('customers/', views.customer, name="customer"),
    path('customers/new', views.new_customer_entry, name="new-customer"),
    path('cell-phones/', views.cell_phone, name="cell-phone"),
    path('cell-phones/new', views.new_cellphone_entry, name="new-cellphone"),
    path('cell-phones/repair-order/<str:pk>/delivered', views.mark_as_delivered, name="mark-as-delivered"),
    path('tickets/', views.tickets, name="tickets"),
    path('new-entry/', views.new_entry, name="new-entry"),
    path('technician/', views.technician_page, name="technician-page"),
    path('technician/repair-order/<str:pk>', views.diagnose_repair_order, name="diagnose-repair-order"),
    path('technician/repair-order/<str:pk>/fixed', views.mark_as_fixed, name="mark-as-fixed"),

    path('password-forgotten/', views.password_forgotten, name="password-forgotten"),
]

smartfix/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('itsc_celulares.urls'))
]

itsc_celulares/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class Technician(models.Model):
    username = models.OneToOneField(User, null=True, blank=False, on_delete=models.SET_NULL)
    first_name = models.CharField(max_length=100, null=False)
    last_name = models.CharField(max_length=100, null=False)
    phone = models.CharField(max_length=20, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.first_name


class Customer(models.Model):
    first_name = models.CharField(max_length=100, null=False, blank=False)
    last_name = models.CharField(max_length=100, null=False, blank=False)
    primary_phone_number = models.CharField(max_length=20, null=False, blank=False)
    secondary_phone_number = models.CharField(max_length=20, null=False, blank=True)
    email = models.EmailField()

    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return self.full_name()


class CellPhone(models.Model):
    brand = models.CharField(max_length=100, null=False, blank=False)
    model = models.CharField(max_length=100, null=False, blank=False)
    serial_number = models.CharField(max_length=100, null=False, blank=False)
    problem_description = models.TextField(null=False, blank=False)
    diagnosis = models.TextField(null=False, blank=True)
    customer = models.ForeignKey(Customer, on_delete=models.DO_NOTHING)

    def device_brand_model_str_rep(self):
        return f"{self.brand} {self.model}"

    def __str__(self):
        return self.brand


class RepairOrder(models.Model):
    RECEIVED = "RECEIVED"
    IN_DIAGNOSIS = "IN DIAGNOSIS"
    IN_REPAIR = "IN REPAIR"
    READY_FOR_DELIVERY = "READY FOR DELIVERY"
    DELIVERED = "DELIVERED"

    REPAIR_ORDER_STATUS = [
        (RECEIVED, "Recibido"),
        (IN_DIAGNOSIS, "En Diagnostico"),
        (IN_REPAIR, "En Reparacion"),
        (READY_FOR_DELIVERY, "Listo para entrega"),
        (DELIVERED, "Entregado")
    ]

    technician = models.ForeignKey(Technician, models.SET_NULL, null=True)
    device = models.ForeignKey(CellPhone, on_delete=models.DO_NOTHING)
    date_created = models.DateTimeField(auto_now_add=True)
    order_status = models.CharField(max_length=100, choices=REPAIR_ORDER_STATUS, default=RECEIVED)

    def __str__(self):
        return f"{self.device.brand} - {self.device.customer}"

itsc_celulares/forms.py
import re

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _

from itsc_celulares.models import *


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "password1", "password2"]
        labels = {
            "username": _("Usuario"),
            "first_name": _("Nombre"),
            "last_name": _("Apellido"),
            "password1": _("Contraseña"),
            "password2": _("Reingresar contraseña"),
        }

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("El usuario ya existe")
        return username

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')
        if len(password1) < 8:
            raise forms.ValidationError("La contraseña debe contener al menos 8 caracteres y debe ser alfanumerica")
        return password1

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 != password1:
            raise forms.ValidationError("Las contraseñas no coinciden")
        return password1


class CustomerEntryForm(ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'
        labels = {
            "first_name": _("Nombre"),
            "last_name": _("Apellido"),
            "primary_phone_number": _("Número de telefono primario"),
            "secondary_phone_number": _("Número de telefono secundario"),
            "email": _("Correo electrónico"),
        }

    def clean_primary_phone_number(self):
        primary_phone_number = self.cleaned_data.get('primary_phone_number')
        # secondary_phone_number = self.cleaned_data.get('secondary_phone_number')
        phone_number_regex = re.compile(r'(^[0-9]{7}$|^[0-9]{10}$)')
        if not phone_number_regex.match(primary_phone_number):
            raise forms.ValidationError("Debe introducir un numero de telefono valido.")

        return primary_phone_number

    def clean_secondary_phone_number(self):
        secondary_phone_number = self.cleaned_data.get('secondary_phone_number')
        phone_number_regex = re.compile(r'(^[0-9]{7}$|^[0-9]{10}$)')
        if not phone_number_regex.match(secondary_phone_number):
            raise forms.ValidationError("Debe introducir un numero de telefono valido.")
        return secondary_phone_number


class CellPhoneEntryForm(ModelForm):
    class Meta:
        model = CellPhone
        fields = '__all__'
        labels = {
            "brand": _("Marca"),
            "model": _("Modelo"),
            "serial_number": _("Número de serie"),
            "problem_description": _("Descripción del problema"),
            "diagnosis": _("Diagnóstico"),
            "customer": _("Cliente"),
        }


class NewEntryForm(ModelForm):
    class Meta:
        model = RepairOrder
        fields = '__all__'
        labels = {
            "technician": _("Técnico"),
            "device": _("Dispositivo"),
            "order_status": _("Status"),
        }

itsc_celulares/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *
from .decorators import *


# Create your views here.

@unauthenticated_user
# @allowed_users(allowed_roles=['admin', 'technician'])
def login_page(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.info(request, "Credenciales invalidas. Intente nuevamente!")
            return redirect('login')
    return render(request, "itsc_celulares/login.html")


def logout_user(request):
    logout(request)
    return redirect('login')


@login_required(login_url='login')
@admin_only
def home(request):
    repair_orders = RepairOrder.objects.all()
    repair_orders_received = repair_orders.filter(order_status="RECEIVED").count()
    repair_orders_in_diagnosis = repair_orders.filter(order_status="IN DIAGNOSIS").count()
    repair_orders_in_repair = repair_orders.filter(order_status="IN REPAIR").count()
    repair_orders_ready_for_delivery = repair_orders.filter(order_status="READY FOR DELIVERY").count()
    repair_orders_delivered = repair_orders.filter(order_status="DELIVERED").count()
    context = {
        'repair_orders': repair_orders,
        'repair_orders_received': repair_orders_received,
        'repair_orders_in_diagnosis': repair_orders_in_diagnosis,
        'repair_orders_in_repair': repair_orders_in_repair,
        'repair_orders_ready_for_delivery': repair_orders_ready_for_delivery,
        'repair_orders_delivered': repair_orders_delivered,
    }

    return render(request, "itsc_celulares/dashboard.html", context)


@login_required(login_url='login')
@allowed_users(allowed_roles=['admin'])
@admin_only
def users(request):
    technicians = Technician.objects.all()
    context = {'technicians': technicians}
    return render(request, "itsc_celulares/users.html", context)


@login_required(login_url='login')
@admin_only
def register_new_user(request):
    form = UserRegistrationForm()
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users')
        else:
            for error in form.errors.values():
                messages.error(request, error)

    context = {'form': form}
    return render(request, "itsc_celulares/register_new_user.html", context)


@login_required(login_url='login')
@admin_only
def customer(request):
    customers = Customer.objects.all()
    context = {'customers': customers}
    return render(request, "itsc_celulares/customers.html", context)


@login_required(login_url='login')
@admin_only
def new_customer_entry(request):
    customer_form = CustomerEntryForm()
    if request.method == "POST":
        customer_form = CustomerEntryForm(request.POST)
        if customer_form.is_valid():
            customer_form.save()
            return redirect('new-cellphone')

        else:
            for error in customer_form.errors.values():
                messages.error(request, error)

    context = {'form': customer_form}
    return render(request, "itsc_celulares/new_customer_entry.html", context)


@login_required(login_url='login')
@admin_only
def cell_phone(request):
    repair_order_cellphones = RepairOrder.objects.select_related('device').all()

    context = {'repair_order_cellphones': repair_order_cellphones}
    return render(request, "itsc_celulares/cell_phones.html", context)


@login_required(login_url='login')
@admin_only
def new_cellphone_entry(request):
    cellphone_form = CellPhoneEntryForm()
    if request.method == "POST":
        cellphone_form = CellPhoneEntryForm(request.POST)
        if cellphone_form.is_valid():
            cellphone_form.save()
            return redirect('new-entry')
    context = {'form': cellphone_form}
    return render(request, "itsc_celulares/new_cell_phone_entry.html", context)


@login_required(login_url='login')
@admin_only
def new_entry(request):
    form = NewEntryForm()
    if request.method == "POST":
        form = NewEntryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    context = {'form': form}
    return render(request, "itsc_celulares/new_entry.html", context)


@login_required(login_url='login')
@allowed_users(allowed_roles=['technician'])
def technician_page(request):
    is_technician = request.user.groups.filter(name='technician').exists()
    technician_id = request.user.technician.id
    repair_orders = RepairOrder.objects.all()
    technician_repair_orders = repair_orders.filter(technician_id=technician_id)

    context = {
        'is_technician': is_technician,
        'repair_orders': repair_orders,
        'technician_repair_orders': technician_repair_orders,
    }
    return render(request, "itsc_celulares/technican_page.html", context)


@login_required(login_url='login')
@allowed_users(allowed_roles=['technician'])
def diagnose_repair_order(request, pk):
    repair_order = RepairOrder.objects.get(id=pk)
    device = CellPhone.objects.get(id=repair_order.device.id)
    form = CellPhoneEntryForm(instance=device)
    if request.method == "POST":
        form = CellPhoneEntryForm(request.POST, instance=device)
        if form.is_valid():
            repair_order.order_status = "IN DIAGNOSIS"
            repair_order.save()
            form.save()

            return redirect('technician-page')

    context = {'form': form}
    form.fields['brand'].widget.attrs['readonly'] = True
    form.fields['model'].widget.attrs['readonly'] = True
    form.fields['serial_number'].widget.attrs['readonly'] = True
    form.fields['problem_description'].widget.attrs['readonly'] = True
    form.fields['customer'].widget.attrs['readonly'] = True

    return render(request, "itsc_celulares/diagnose_repair_order.html", context)


@login_required(login_url='login')
@allowed_users(allowed_roles=['technician'])
def mark_as_fixed(request, pk):
    repair_order = RepairOrder.objects.get(id=pk)
    if request.method == "POST":
        repair_order.order_status = "READY FOR DELIVERY"
        repair_order.save()
        return redirect('technician-page')

    return render(request, "itsc_celulares/technican_page.html")


def tickets(request):
    repair_orders = RepairOrder.objects.all()
    context = {'repair_orders': repair_orders}
    return render(request, "itsc_celulares/tickets.html", context)


def remove_user(request, pk):
    user = Technician.objects.get(id=pk)

    if request.method == "POST":
        user.username.is_active = False
        user.username.save()
        user.delete()

        return redirect('users')

    context = {'user': user}

    return render(request, "itsc_celulares/delete_user.html", context)


def mark_as_delivered(request, pk):
    repair_order = RepairOrder.objects.get(id=pk)

    if request.method == "POST":
        repair_order.order_status = "DELIVERED"
        repair_order.save()

        return redirect('cell-phone')

    return render(request, "itsc_celulares/cell_phones.html")


def password_forgotten(request):
    return render(request, "itsc_celulares/password_forgotten.html")

itsc_celulares/templates/itsc_celulares/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ITSC Celulares</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>CRM</title>
    <style>
        body {
        background-color: #B2E0D8;
        margin: 0;
        padding: 0;
        height: 100vh;
        display: flex;
        align-items: stretch;
      }

      .container-fluid {
        display: flex;
        width: 100%;
        height: 100%;
        padding: 0;
      }

      .aside {
        background: white;
        padding: 30px;
        border-radius: 8px;
        box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
        width: 300px;
        height: 100%;
      }

      h4 {
        text-align: center;
        margin-bottom: 20px;
        color: #333;
      }

      .nav {
        list-style-type: none;
        padding: 0;
        flex-grow: 1;
      }

      .nav-item {
        margin-bottom: 10px;
      }

      .nav-link {
        display: block;
        padding: 10px;
        color: #555;
        text-decoration: none;
        border-radius: 4px;
      }

      .nav-link.active {
        background-color: #007BFF;
        color: white;
      }

      .nav-link:hover {
        background-color: #e7f1ff;
        color: #007BFF;
      }

      .content {
        flex: 1;
        padding: 20px;
        background-color: white;
        border-radius: 8px;
        box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
        margin: 20px 20px;
        overflow-y: auto;
      }
      h5 {
          text-align: center;
      }
    </style>
  </head>
  <body>

    <div class="container-fluid">
        <aside class="aside">
            <h5>ITSC Celulares</h5>
            <ul class="nav flex-column">
                {% if request.user.is_staff %}
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'home' %}">Dashboard</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users' %}">Usuarios</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'customer' %}">Clientes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cell-phone' %}">Celulares</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'tickets' %}">Tickets</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'technician-page' %}">Tickets</a>
                </li>
                {% endif %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Cerrar Sesión</a>
                </li>
            </ul>
        </aside>
        <div class="content">
            <h1 style="text-align: right">Bienvenido, {{ request.user }}</h1>
{#            <h2>{% if is_technician %}Ordenes de reparación{% else %}Activdad{% endif %}</h2>#}
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

itsc_celulares/templates/itsc_celulares/cell_phones.html
{% extends 'itsc_celulares/base.html' %}


{% block content %}
    <h3>Celulares</h3>
        <style>
    .btn {
        margin-left: 1200px;
    }

    #mark-as-delivered {
        margin: 0;
    }

    </style>

    <a href="{% url 'new-cellphone' %}" class="btn btn-primary" role="button" aria-disabled="true">Nuevo</a>

    <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Marca</th>
      <th scope="col">Modelo</th>
      <th scope="col">Descripción del problema</th>
      <th scope="col">Diagnostico</th>
      <th scope="col">Status</th>
      <th scope="col">Cliente</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  {% for repair_order_cellphone in repair_order_cellphones %}
      <tr>
      <th scope="row">{{ repair_order_cellphone.device.id }}</th>
      <td>{{ repair_order_cellphone.device.brand }}</td>
      <td>{{ repair_order_cellphone.device.model }}</td>
      <td>{{ repair_order_cellphone.device.problem_description }}</td>
      <td>{{ repair_order_cellphone.device.diagnosis }}</td>
      <td>{{ repair_order_cellphone.get_order_status_display }}</td>
      <td>{{ repair_order_cellphone.device.customer.full_name }}</td>
      <td>
        <form method="POST" action="{% url 'mark-as-delivered' repair_order_cellphone.id %}">
            {% csrf_token %}
            <button type="submit" id="mark-as-delivered" class="btn btn-info" {% if repair_order_cellphone.order_status == "DELIVERED" %}disabled{% endif %}>Marcar como entregado</button>
        </form>
      </td>

  {% endfor %}

    </tr>
  </tbody>
</table>
{% endblock %}

itsc_celulares/templates/itsc_celulares/customers.html
{% extends 'itsc_celulares/base.html' %}
{% block content %}
    <style>

        .btn {
            margin-left: 1200px;
        }

    </style>

    <h3>Clientes</h3>

    <a href="{% url 'new-customer' %}" class="btn btn-primary" role="button" aria-disabled="true">Nuevo</a>

    <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre</th>
      <th scope="col">Apellido</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  {% for customer in customers %}
      <tr>
      <th scope="row">{{ customer.id }}</th>
      <td>{{ customer.first_name }}</td>
      <td>{{ customer.last_name }}</td>
       <td></td>
{#      {% if technician.username.is_active %}#}
{#      {% endif %}#}
{#      <td><button type="button" class="btn btn-primary btn-actions">Ver</button><button type="button" class="btn btn-danger btn-actions">Eliminar</button></td>#}
  {% endfor %}

    </tr>
  </tbody>
</table>
{% endblock %}

itsc_celulares/templates/itsc_celulares/dashboard.html
{% extends 'itsc_celulares/base.html' %}



{% block content %}
<style>

.dashboard {
    display: flex;
    {#flex-direction: column; /* Cambia la dirección del flujo a columna */#}
    {#align-items: center; /* Centra los recuadros horizontalmente */#}
    gap: 10px; /* Espacio entre los recuadros */
    width: 100%; /* Ajusta el ancho del contenedor principal */
    margin-top: 50px;
}

.card {
    width: 90%; /* Ajusta el ancho de cada recuadro */
    border-radius: 10px;
    padding: 15px; /* Aumenta el padding para hacer los recuadros más grandes */
    color: #333;
    text-align: center;
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
}

.card h3 {
    margin: 0;
    font-size: 1.5em; /* Aumenta el tamaño del texto del título */
}

.card p {
    font-size: 2.5em; /* Aumenta el tamaño del texto del número */
    margin: 10px 0 0;
}

/* Colores pastel basados en azul, verde y rojo */
.received {
    background-color: #a8dadc; /* Pastel azul */
}

.in-diagnosis {
    background-color: #c3e6cb; /* Pastel verde */
}

.in-repair {
    background-color: #f5c6cb; /* Pastel rojo */
}

.ready-for-delivery {
    background-color: #d4edda; /* Pastel verde claro */
}

.delivered {
    background-color: #cce5ff; /* Pastel azul claro */
}

.new-entry-container{
    display: flex;
    flex-direction: row-reverse;
}


#new-entry {
     display: inline-block;  /* Permite ajustar el ancho y alto */
    padding: 10px 20px;     /* Espacio alrededor del texto */
    text-decoration: none;  /* Quitar subrayado del enlace */
    background-color: #007bff; /* Color de fondo del botón */
    color: white;           /* Color del texto */
    border: 1px solid #007bff; /* Borde del botón */
    border-radius: 4px;     /* Borde redondeado */
    font-size: 16px;        /* Tamaño del texto */
    text-align: center;     /* Alineación del texto */
    transition: background-color 0.3s, color 0.3s; /* Transición suave */
}




</style>


{#        Tabla De celulares con opción de actualizar estados perfil del tecnico#}

        {% if request.user.is_staff %}
            <h2>Actividad</h2>
            <div class="new-entry-container">
            <a href="{% url 'new-customer' %}" class="btn btn-info" id="new-entry" role="button" aria-disabled="true">Nueva Entrada</a>
            </div>

        <div class="dashboard">

        <div class="card received">
            <h3>Recibido</h3>
            <p>{{ repair_orders_received }}</p>
        </div>
        <div class="card in-diagnosis">
            <h3>En Diagnóstico</h3>
            <p>{{ repair_orders_in_diagnosis }}</p>
        </div>
        <div class="card in-repair">
            <h3>En Reparación</h3>
            <p>{{ repair_orders_in_repair }}</p>
        </div>
        <div class="card ready-for-delivery">
            <h3>Listo para Entrega</h3>
            <p>{{ repair_orders_ready_for_delivery }}</p>
        </div>
        <div class="card delivered">
            <h3>Entregado</h3>
            <p>{{ repair_orders_delivered }}</p>
        </div>
    </div>
    {% endif %}


{% endblock %}

itsc_celulares/templates/itsc_celulares/technican_page.html
{% extends "itsc_celulares/base.html" %}
{% block content %}
     <style>
  .container {
        font-family: Arial, sans-serif;
        overflow: hidden;
        background: white;
        margin-top: 100px;
        display: flex;
        flex-wrap: wrap;
        color: #4d4852;
        width: 100%;
        justify-content: space-evenly;
    }


    .ticket {
        border: 1px solid #ddd;
        padding: 10px;
        margin: 10px;
        border-radius: 5px;
        background: #d3eaff; /* Azul pastel */
        width: 30%;
        box-sizing: border-box;
    }

    .ticket h2 {
        margin: 0;
        color: #333;
    }

    .ticket p {
        margin: 5px 0;
    }

    .ticket button {
        display: inline-block;
        margin-top: 15px;
        padding: 10px;
        background: #0e836a; /* Rojo pastel */
        color: white;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }

    .ticket .btn-info,
    .btn-success {
        display: inline-block;
        padding: 8px 16px;
        background-color: #169ede; /* Azul pastel */
        color: white;
        text-decoration: none;
        border: none;
        cursor: pointer;
        border-radius: 4px;
        text-align: center;
    }

</style>

    <h2>Ordenes de reparación</h2>
    <div class="container">

        {% if technician_repair_orders %}
            {% for repair_order in technician_repair_orders %}
            <div class="ticket" id="ticket-1">
                <h2>Orden {{ repair_order.id }}</h2>
                <p><strong>Status:</strong> {{ repair_order.get_order_status_display }}</p>
                <p><strong>Cliente:</strong> {{ repair_order.device.customer.full_name }}</p>
                <p><strong>Dispositivo:</strong> {{ repair_order.device.device_brand_model_str_rep }}</p>
                <p><strong>Descripción del problema:</strong> {{ repair_order.device.problem_description }}</p>
                <p><strong>Diagnóstico:</strong> {{ repair_order.device.diagnosis }}</p>
                <p><strong>Fecha de Asignación:</strong> {{ repair_order.date_created | date:"d-m-Y" }}</p>
                <a href="{% url 'diagnose-repair-order' repair_order.id %}"><button class="btn btn-info" {% if repair_order.order_status == "READY FOR DELIVERY" %}disabled{% endif %}>Diagnosticar</button></a>
                <form method="POST" action="{% url 'mark-as-fixed' repair_order.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-success" {% if repair_order.order_status == "READY FOR DELIVERY" %}disabled{% endif %}>Marcar como reparado</button>
                </form>

            </div>
            {% endfor %}
        {% else %}
        <p>No posee Ordenes de reparacion</p>
    {% endif %}
    </div>

{% endblock %}

itsc_celulares/templates/itsc_celulares/tickets.html
{% extends "itsc_celulares/base.html" %}
{% block content %}

    <style>
        .tickets-container {
            display: flex;
            flex-direction: column;
            flex-wrap: wrap; /* Evitar que las tarjetas se envuelvan en varias líneas */
            gap: 20px; /* Espacio entre las tarjetas */
            overflow-x: hidden;
        }

        .ticket {
            background-color: #fff;
            border: 1px solid #ddd;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            padding: 20px;
            width: 300px; /* Ancho fijo de la tarjeta */
            margin-bottom: 20px; /* Espacio entre tarjetas */
        }

        .ticket h2 {
            font-size: 18px;
            margin-top: 0;
        }

        .ticket p {
            font-size: 14px;
            color: #666;
        }
    </style>

{% for repair_order in repair_orders %}
    <div class="tickets-container">
    <div class="ticket">
        <h2>Orden de Reparación # {{ repair_order.id }}</h2>
        <p><strong>Tecnico asignado: </strong>{{ repair_order.technician.username }}</p>
        <p><strong>Dispositivo: </strong>{{ repair_order.device.device_brand_model_str_rep }}</p>
        <p><strong>Cliente: </strong>{{ repair_order.device.customer.full_name }}</p>
        <p><strong>Fecha de entrada: </strong>{{ repair_order.date_created | date:"d-m-Y" }}</p>
        <p><strong>Status: </strong>{{ repair_order.get_order_status_display }}</p>
    </div>

{% endfor %}
{% endblock %}